### ISSUE TITLE
Job bulk_create

### ISSUE THREAD

**Issue by iyawnis** [dabapps/django-db-queue#23]
Current `Job` creation depends on .save() to be called, as a result processing jobs created using `bulk_create` causes django-level exceptions. 

Either the Query manager should be overridden to return `UnsupportedOperation` or the code refactored to work with bulk_create

**Comment by j4mie** [comment]
Six years later (!) I've added a note about this to the README: https://github.com/dabapps/django-db-queue/blob/master/README.md#gotcha-bulk_create
