### ISSUE TITLE
Django model utils > 2.3.1

### ISSUE THREAD

**Issue by dhitaj** [dabapps/django-db-queue#24]
Can django model utils version be greater than 2.3.1 without breaking anything ? In the application I am developing I have a strict requirement for django model utils at least 3.x.x

**Comment by dhitaj** [comment]
As far as I have seen that is used only for Choices in the models so I guess that 2.3.1 is not a strict requirement for you library.

**Comment by j4mie** [comment]
This dependency has been removed in 2.0.0
