### ISSUE TITLE
Add user field to Job model

### ISSUE THREAD

**Issue by johncmacy** [dabapps/django-db-queue#48]
Would you consider adding a nullable ForeignKey field to store the user that a job belongs to?

``` py
class Job(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='jobs')
    ...
```

It would then be possible to assign users to jobs within views that create them, or from any other context in which the user is known:

``` py
def my_view(request):
    job = Job.objects.create(name='my_job', user=request.user)
    ...
```

I realize I can subclass `Job` and add it myself:

``` py
class JobWithUser(Job):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='jobs')
```

However, it would be more convenient for anyone who wants this functionality if it were available out-of-the-box.

**Comment by j4mie** [comment]
This is what the `workspace` is for:

```
Job.objects.create(name="my_job", workspace={"user_id": user.id})
```

And if you need all the jobs "owned" by a user:

```
Job.objects.filter(workspace__user_id=user.id)
```

I'd be against adding an explicit FK to User because there's nothing "special" about User - meaningful relationships between Jobs and other parts of your schema are going to be different depending on the requirements of your project. Why "User" and not "Organisation" or "Team" or "Widget" or anything else? The job's `workspace` is intended to be a flexible way of relating Jobs to other objects without needing explicit FKs to everything.

**Comment by johncmacy** [comment]
Ah, that makes perfect sense, and is a much better solution than what I was proposing due to its flexibility.

I think it would help to clarify this in the documentation, as the way it's currently written led me to dismiss it as just a way for tasks within a job to communicate between each other. Something like:

---

### Workspace

The *workspace* is an area that can be used 1) to provide additional arg/kwargs to task functions, and 2) to categorize jobs with additional metadata. It is implemented as a Python dictionary, available on the `job` instance passed to tasks as `job.workspace`. The initial workspace of a job can be empty, or can contain some parameters that the tasks require (for example, API access tokens, account IDs etc).

When creating a Job, the workspace is passed as a keyword argument:

```python
Job.objects.create(name='my_job', workspace={'key': value})
```

Then, the task function can access the workspace to get the data it needs to perform its task:

```python
def my_task(job):
    cats_import = CatsImport.objects.get(pk=job.workspace['cats_import_id']
```

Tasks within a single job can use the workspace to communicate with each other. A single task can edit the workspace, and the modified workspace will be passed on to the next task in the sequence. For example:

    def my_first_task(job):
        job.workspace['message'] = 'Hello, task 2!'

    def my_second_task(job):
        logger.info("Task 1 says: %s" % job.workspace['message'])

The workspace can be queried like any [JSONField](https://docs.djangoproject.com/en/3.2/topics/db/queries/#querying-jsonfield). For instance, if you wanted to display a list of jobs that a certain user had initiated, add `user_id` to the workspace when creating the job:

```python
Job.objects.create(name='foo', workspace={'user_id': request.user.id})
```

Then filter the query with it in the view that renders the list:

```python
user_jobs = Job.objects.filter(workspace__user_id=request.user.id)
```

**Comment by j4mie** [comment]
That would be brilliant @johncmacy - love the way you've worded that. Would you like to open a PR with that addition or would you prefer me to?

**Comment by johncmacy** [comment]
I'd be happy to as long as there's no formatters involved :)
