### ISSUE TITLE
stdout on worker start incorrectly describes the rate limit as rate per second

### ISSUE THREAD

**Issue by collinr3** [dabapps/django-db-queue#53]
As is 
`self.stdout.write(
            'Starting job worker for queue "%s" with rate limit %s/s'
            % (queue_name, rate_limit_in_seconds)
        )
`
proposed
``self.stdout.write(
            'Starting job worker for queue "%s" with rate limit of one job per %s second(s)'
            % (queue_name, rate_limit_in_seconds)
        )
`

If you're ok with the wording, I'm happy to submit a Pull request to correct this.

**Comment by jordaneb** [comment]
Hi @collinr3,

Thanks for taking the time to open this issue.

You're absolutely right it should be "1 job per n seconds" and not what it states currently.

A pull request would be much appreciated if you are able 😄 

Stick a comment in here when there is a PR and we'll get it reviewed.

**Comment by collinr3** [comment]
Hi @jordaneb,

Pull request ready for your review.
